language: java

os: osx
osx_image: xcode9.3

before_script:
  - wget https://github.com/google/j2objc/releases/download/2.3.1/j2objc-2.3.1.zip
  - unzip j2objc-2.3.1.zip
  - rm local.properties
  - echo "j2objc.home=./j2objc-2.3.1/" > local.properties

script:
    - ./gradlew -b j2objc.gradle clean :j2objcAssemble -x test

after_success:
  - git config --global user.email "a.urusihara@gmail.com"
  - git config --global user.name "Akihiro Urushihara"
  - cd ./build/j2objcOutputs/
  - git init
  - git add --all
  - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - git remote add origin https://${AZ_TOKEN}@dev.azure.com/SocialHub/ObjCBinary/_git/ObjCBinary
  - git push -f origin master
